### ISSUE TITLE
Merge QuRouter into QTS

### ISSUE THREAD

**Issue by chanjuping** [PenangScienceCluster/qnap-digital-library#6]
**Is your feature request related to a problem? Please describe.**
The prevalence of two admin login pages with two distinct logins is confusing.

**Describe the solution you'd like**
Merge QuRouter into QTS and allow both to be accessed from the same interface.

**Describe alternatives you've considered**
In QTS set up a link to a different port to QuRouter.

**Additional context**
Remote support is currently only possible at the QTS landing page where 192.168.100.100 is standard. Placing QuRouter at a separate IP address also hampers remote support via VPN to the same devices.

**Comment by KahJunC** [comment]
Hi JuPing, 
Except first time , user need to finish router initial process by route login page.
After that , user can only operator QTS one system and operator router setting by "QuRouter" QPKG in QTS Web UI.
If user would like to shutdown QTS and only use router function. User can access router by router login page as well.

**Comment by chanjuping** [comment]
Any way to streamline this to only one login? It really is confusing to have two separate admin pages at first boot. And now to grab diagnostic data, I presumed I would have to use the separate server hosted from 192.168.100.1.

If it is already possible to have them both be in the same interface, this will resolve many usability issues already.

**Comment by KahJunC** [comment]
You hope everything configure by one login page including router initial? 
Or after Initial the router , configuration Router and NAS can be into same Page?

**Comment by chanjuping** [comment]
The first one. So for example the sticker on the back only needs to show the default SSID and password, and one login for admin. Subsume the account in QuRouter into QTS, since QTS looks like the general purpose OS here.

**Comment by KahJunC** [comment]
Thanks for your suggestion,
If you powered on the QMiro, but didn't press power button, 
The router will be on, but not NAS
So you can only access to QuRouter without any NAS Function,
This is why we design have 2 pages
